AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-sam-01

  Sample SAM Template for aws-sam-01
  
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  DynamoStackA:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DynamoStackA
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: account
          AttributeType: S
        - AttributeName: settings
          AttributeType: S
      KeySchema:
        - KeyType: HASH
          AttributeName: account
        - KeyType: RANGE
          AttributeName: settings
      

Outputs:
 MyStackADynamoArn:
    Description: My DynamoDb Arn
    Value: !GetAtt DynamoStackA.Arn
    Export:
      Name: MyStackADynamoArn
 MyStackADynamoName:
    Description: My DynamoDb Name
    Value: !Ref DynamoStackA
    Export:
      Name: MyStackDynamoName
