AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  stack-b

  Sample SAM Template for stack-b
  
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function 
    Connectors:
      ConnUserTable:
        Properties:
          Destination:
            - Type: AWS::DynamoDB::Table
              Arn: 
                Fn::ImportValue:  MyStackADynamoArn
          Permissions:
            - Read
            - Write
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Environment:
            Variables:
              MyDynamoDbName: !ImportValue MyStackDynamoName
      Architectures:
        - x86_64
      Events:
        CreateUser:
          Type: Api 
          Properties:
            Path: /createUser
            Method: POST
          
